### ISSUE TITLE
能否在php镜像默认添加composer和git

### ISSUE THREAD

**Issue by chase577** [suyar/docker-php#2]
看下能不能在php镜像默认添加composer和git呢，常用的是启动容器后进去里面composer安装一些第三方包，项目有git，在容器里面composer没有git环境composer也会报错

**Comment by suyar** [comment]
> 看下能不能在php镜像默认添加composer和git呢，常用的是启动容器后进去里面composer安装一些第三方包，项目有git，在容器里面composer没有git环境composer也会报错

我个人有两点想法：
1. 自己根据需要，进行二次构建，自己写个Dockerfile
2. 我会考虑加到 辅助镜像 或 集成镜像 里，但是基础镜像是不会添加额外的软件的

**Comment by chase577** [comment]
> > 看下能不能在php容器镜像添加默认composer和git呢，常用的是启动后进入composer里面安装一些第三方包，项目有git，在container里面composer没有git环境composer也报错
> 
> 我个人有两点想法：
> 
> 1. 自己根据需要，进行二次构建，自己写个Dockerfile
> 2. 我会考虑添加到辅助镜像或集成镜像里，但是基础镜像是不会添加额外的软件的

是的，我在使用集成镜像的时候出现缺少git的错误

**Comment by suyar** [comment]
> 是的，我在使用集成镜像的时候出现缺少git的错误

麻烦告知下具体出现的镜像版本和出错的demo，我排查下，composer不一定需要使用git吧

**Comment by chase577** [comment]
> > 是的，我在使用集成镜像的时候出现缺少git的错误
> 
> 麻烦告知下具体出现的镜像版本和出错的demo，我排查下，composer不一定需要使用git吧

suyar/php:7.4-integration

**Comment by chase577** [comment]
![ce51b9010dda804bc1d676d48784650](https://github.com/suyar/docker-php/assets/37997987/c0f3370a-e1e8-4d64-8394-8e7ed5bd68ba)
查了一下原因是没安装git

**Comment by suyar** [comment]
![image](https://github.com/suyar/docker-php/assets/15704489/495e8bc1-7f3e-44d4-a135-51fcdab4f79a)

我这边引入正常，你是在composer里面使用了私有仓库的包是吧？如果不是，请尝试 `sudo docker pull suyar/php:7.4-integration` 把镜像更新到最新版本，然后重试。

私有包示例：
![image](https://github.com/suyar/docker-php/assets/15704489/bafa9397-2513-4d14-b1ef-7d44f28acfcd)

**Comment by chase577** [comment]
我composer里面没有使用私有仓库，原因是我的项目使用了git，我直接起一个容器进去直接composer安装包也是正常可以安装的

![image](https://github.com/suyar/docker-php/assets/37997987/a116ddfa-6a8a-4304-8f8c-ae371c415e1e)

**Comment by suyar** [comment]
可以先自己安装一下git，我觉得镜像已经有点大了
